name: "Ollama Code Review"
description: "Revisa archivos de código con un LLM local (Ollama) y genera reportes."
author: "tu-usuario"

inputs:
  model:
    description: "Modelo Ollama (p.ej. qwen2.5-coder:7b)"
    required: true
    default: "qwen2.5-coder:7b"
  server_url:
    description: "URL del servidor Ollama"
    required: true
    default: "http://127.0.0.1:11434"

  file_glob:
    description: "Patrón glob fallback para elegir archivos"
    required: false
    default: "**/*.{ts,tsx,js,jsx,py,cs,java,go,rs}"
  exclude_glob:
    description: "Patrones de exclusión (multilínea)"
    required: false
    default: |
      **/node_modules/**
      **/dist/**
      **/build/**
      **/.next/**
      **/coverage/**
      **/ollama-review-report/**
      **/.git/**
  file_list:
    description: "Lista de archivos (multilínea)"
    required: false
    default: ""
  file_list_path:
    description: "Ruta a archivo con paths (uno por línea)"
    required: false
    default: ""

  fail_on_critica:
    description: "Falla si hay al menos una CRÍTICA"
    required: false
    default: "true"
  retention_days:
    description: "Días de retención del artifact"
    required: false
    default: "7"

  # Perf / resiliencia
  request_timeout_ms:
    description: "Timeout por archivo (ms)"
    required: false
    default: "300000"
  max_bytes_per_file:
    description: "Máximo de bytes por archivo (truncado)"
    required: false
    default: "200000"
  ollama_num_predict:
    description: "Tokens de salida"
    required: false
    default: "256"
  ollama_num_ctx:
    description: "Contexto"
    required: false
    default: "1536"
  ollama_temperature:
    description: "Temperatura"
    required: false
    default: "0"
  review_max_concurrency:
    description: "Archivos en paralelo"
    required: false
    default: "1"

runs:
  using: "node20"
  main: "dist/index.js"

outputs:
  report_dir:
    description: "Directorio donde se generó el reporte"
  summary_md_path:
    description: "Ruta al resumen Markdown para comentar en PR/commit"

branding:
  color: "blue"
  icon: "search"
