name: "Ollama Code Review"
description: "Revisa código con Ollama y genera reporte web + JSON + anotaciones."
author: "bernherre"
inputs:
  model:
    description: "Modelo Ollama (ej: qwen2.5-coder:7b)"
    required: true
    default: "qwen2.5-coder:7b"
  server_url:
    description: "URL del servidor Ollama"
    required: true
    default: "http://127.0.0.1:11434"

  file_glob:
    description: "Glob de archivos (fallback)"
    required: false
    default: "**/*"
  exclude_glob:
    description: "Patrones de exclusión (multilínea)"
    required: false
    default: ""
  file_list:
    description: "Lista de archivos (multilínea)"
    required: false
    default: ""
  file_list_path:
    description: "Ruta a archivo con paths (uno por línea)"
    required: false
    default: ""

  fail_on_critica:
    description: "Fallar si hay issues CRÍTICA"
    required: false
    default: "true"
  retention_days:
    description: "Días de retención del artifact"
    required: false
    default: "7"

  # Resiliencia / performance
  request_timeout_ms:
    description: "Timeout por archivo (ms)"
    required: false
    default: "300000"
  max_bytes_per_file:
    description: "Máximo de bytes por archivo (truncado)"
    required: false
    default: "307200"
  ollama_num_predict:
    description: "Tokens de salida (num_predict)"
    required: false
    default: "512"
  ollama_num_ctx:
    description: "Contexto (num_ctx)"
    required: false
    default: "2048"
  ollama_temperature:
    description: "Temperatura"
    required: false
    default: "0"
  review_max_concurrency:
    description: "Máximo de archivos procesados en paralelo"
    required: false
    default: "2"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  color: "blue"
  icon: "shield"
