name: AI Code Review (no Docker)

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "ai-review"
  cancel-in-progress: true

env:
  MODEL: qwen2.5-coder:7b
  NO_PROXY: "127.0.0.1,localhost"
  REVIEW_MAX_CONCURRENCY: "1"  # estabilidad > velocidad (sube a 2 cuando lo veas sólido)

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      # 1) Instala Ollama CLI (sin contenedor)
      - name: Setup Ollama
        uses: ai-action/setup-ollama@v1
        # with:
        #   version: 0.3.14   # opcional, fija versión

      # 2) Cache de modelos
      - name: Cache Ollama models
        uses: actions/cache@v4
        with:
          path: ~/.ollama/models
          key: ollama-${{ runner.os }}-${{ env.MODEL }}
          restore-keys: |
            ollama-${{ runner.os }}-

      # 3) Pull y warm (mantén caliente con keep_alive)
      - name: Pull & warm
        run: |
          ollama pull "${MODEL}"
          curl -sS -X POST http://127.0.0.1:11434/api/chat \
            -H "Content-Type: application/json" \
            -d '{"model":"'"${MODEL}"'","stream":false,"messages":[{"role":"user","content":"ok"}],"keep_alive":"10m"}' \
            | head -c 200

      # 4) Solo PR: archivos cambiados (filtra a código)
      - name: Collect changed files (PR only)
        id: changed
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const pr = context.payload.pull_request;
            const per_page = 100;
            let page = 1, files = [];
            while (true) {
              const { data } = await github.rest.pulls.listFiles({
                ...context.repo, pull_number: pr.number, per_page, page
              });
              files.push(...data);
              if (data.length < per_page) break;
              page++;
            }
            const paths = files
              .filter(f => f.status !== 'removed')
              .map(f => f.filename)
              .filter(p => p.match(/\.(ts|tsx|js|jsx|py|cs|java|go|rs)$/i)); // solo código
            fs.writeFileSync('changed-files.txt', paths.join('\n'));
            core.setOutput('count', String(paths.length));
            core.setOutput('path', 'changed-files.txt');

      - name: Debug changed count
        if: ${{ github.event_name == 'pull_request' }}
        run: |
            echo "Changed count: ${{ steps.changed.outputs.count || '0' }}"

      # 5) PR con cambiados → usa lista
      - name: Run Ollama Code Review (PR changed files)
        if: ${{ github.event_name == 'pull_request' && steps.changed.outputs.count != '0' }}
        uses: bernherre/checkwithai/action-ollama-codereview@v1
        env:
          REVIEW_MAX_CONCURRENCY: ${{ env.REVIEW_MAX_CONCURRENCY }}
        with:
          model: ${{ env.MODEL }}
          server_url: http://127.0.0.1:11434
          file_list_path: ${{ steps.changed.outputs.path }}
          exclude_glob: |
            **/node_modules/**
            **/dist/**
            **/build/**
            **/.next/**
            **/coverage/**
            **/ollama-review-report/**
            action-ollama-codereview/**
          fail_on_critica: "true"
          retention_days: "7"
          request_timeout_ms: "600000"
          max_bytes_per_file: "200000"
          ollama_num_predict: "192"
          ollama_num_ctx: "1024"
          ollama_temperature: "0"

      # 6) Fallback (push o PR sin cambios de código) → glob solo de código
      - name: Run Ollama Code Review (fallback only code glob)
        if: ${{ github.event_name != 'pull_request' || steps.changed.outputs.count == '0' }}
        uses: bernherre/checkwithai/action-ollama-codereview@v1
        env:
          REVIEW_MAX_CONCURRENCY: ${{ env.REVIEW_MAX_CONCURRENCY }}
        with:
          model: ${{ env.MODEL }}
          server_url: http://127.0.0.1:11434
          file_glob: "src/**/*.{ts,tsx,js,jsx,py,cs,java,go,rs}"
          exclude_glob: |
            **/node_modules/**
            **/dist/**
            **/build/**
            **/.next/**
            **/coverage/**
            **/ollama-review-report/**
            action-ollama-codereview/**
          fail_on_critica: "true"
          retention_days: "7"
          request_timeout_ms: "600000"
          max_bytes_per_file: "200000"
          ollama_num_predict: "192"
          ollama_num_ctx: "1024"
          ollama_temperature: "0"

      - name: Upload review artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama-review
          path: ollama-review-report/**
          retention-days: 7
