name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # No es necesario hacer checkout para release-please
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          # Archivos de configuración en la RAÍZ del repo
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
