name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: rp
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: action-ollama-codereview
          bump-minor-pre-major: true
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"docs","section":"Docs","hidden":false},
             {"type":"chore","section":"Chores","hidden":true}]
